### ISSUE TITLE
Text hierarchy in questions can lead to confusion

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#102]
User’s natural reaction to answering the veteran question was “yes” until they read it more closely. Might be good to make sure we have bolded words in our questions to make it obvious what it is about.

“Are you a **veteran** of the United States?”

Or potentially prefacing questions with the keyword:

“**Veteran Status**. Are you a veteran of the United States?”

**Comment by bengolder** [comment]
I think both of these changes are an improvement.

**Comment by bengolder** [comment]
This is a little awkward, because the labels are already bolded. The default fonts don't seem to have fine gradations of font-weight available, which would allow us to use a "black" typeface that is even heavier than bold (for example, using 800 vs 600). In order to make it `<strong>` tags stand out, we would need to de-emphasize form labels in some way. This could be done with color or with font-weight.

``` css
label { color: #666; }
label strong { color: #000; }
```

Color shift for strong tags in labels
![screen shot 2015-05-20 at 5 35 16 pm](https://cloud.githubusercontent.com/assets/451510/7739511/eb373240-ff16-11e4-92ee-0d97af7ecd17.png)

``` css
label { font-weight: 500; }
label strong { font-weight: 900; }
```

![screen shot 2015-05-20 at 5 39 57 pm](https://cloud.githubusercontent.com/assets/451510/7739539/47070e6a-ff17-11e4-9619-1b4d6480f3ee.png)

``` css
label { font-weight: 300; }
label strong { font-weight: 900; }
```

![screen shot 2015-05-20 at 5 40 49 pm](https://cloud.githubusercontent.com/assets/451510/7739545/63ddbd7c-ff17-11e4-9c01-bd6d90fa86fd.png)
